# Generated by Django 5.0.6 on 2024-07-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
