# Generated by Django 5.0.6 on 2024-07-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_pet_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
