# Generated by Django 5.0.6 on 2024-07-14 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_pet_adopted'),
        ('transaction', '0001_initial'),
        ('user', '0004_remove_usermodel_image_remove_usermodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_details', to='pet.pet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='user.usermodel'),
        ),
    ]
