# Generated by Django 5.0.6 on 2024-07-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_balance_alter_usermodel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='phone',
        ),
    ]
