# Generated by Django 5.0.6 on 2024-07-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usermodel_image_usermodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='phone',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
