# Generated by Django 5.0.6 on 2024-07-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_usermodel_phone_alter_usermodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='image',
        ),
    ]
